# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooanimal',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 3, 18, 57, 2, 818944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='zoocage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 3, 18, 57, 2, 817797, tzinfo=utc)),
        ),
    ]
