# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cages', '0002_auto_20160703_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zooanimal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='zoocage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
